# Generated by Django 5.2.4 on 2025-11-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_default_behaviors'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='experiments/clips/thumbnails/'),
        ),
    ]
